services:

  task-manager:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"
    environment:
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - PRIVATE_KEY_PATH=${PRIVATE_KEY_PATH:-/app/keys/private.pem}
