import os
import json
import asyncio

from pydantic import SecretStr
from langchain_core.messages import HumanMessage
from langchain_openai import AzureChatOpenAI
from browser_use import Agent, Browser, BrowserConfig, Controller
from dotenv import load_dotenv
from pydantic import BaseModel
from pydantic import ValidationError
from lmnr.sdk.laminar import Laminar
from pydantic import BaseModel
from enum import Enum
from get_sections_to_test import TestSection
from retry import retry

load_dotenv()

# this line auto-instruments Browser Use and any browser you use (local or remote)
# Laminar.initialize() # you can also pass project api key here


AGENT_LLM = AzureChatOpenAI(
    model="gpt-4o",
    api_version='2024-10-21',
    azure_endpoint=os.getenv('AZURE_OPENAI_ENDPOINT', ''),
    api_key=SecretStr(os.getenv('AZURE_OPENAI_KEY', '')),
    temperature=0.0,
)


class TestCategory(Enum):
    POSITIVE = "Positive"
    NEGATIVE = "Negative"
    BOUNDARY = "Boundary"
    INTEGRATION = "Integration"
    # PERFORMANCE = "Performance" # NOTE: for now fuck the performance tests


class Priority(Enum):
    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"
    LOWEST = "Lowest"


class GeneratedTestCase(BaseModel):
    test_description: str
    preconditions: str
    test_steps: list[str]
    expected_results: str
    priority: Priority
    # dependencies: list[str]


class GeneratedTestPlan(BaseModel):
    test_cases: list[GeneratedTestCase]


class TestCase(GeneratedTestCase):
    test_id: str # Should be generated by ourselves
    test_category: TestCategory # TODO: should be generated by ourselves


class TestPlan(BaseModel):
    test_cases: dict[TestCategory, list[TestCase]]


def load_test_plan(path: str) -> TestPlan:
    with open(path, "r") as f:
        return TestPlan.model_validate(json.load(f))


def print_test_plan(test_plan: TestPlan) -> str:

    output = ""

    output += "Test Cases:\n"

    for test_category, test_cases in test_plan.test_cases.items():
        output += f"== {test_category.value} ==\n"

        for test_case in test_cases:
            output += f"== {test_case.test_id} ==\n"
            output += f"Category: {test_case.test_category.value}\n"
            output += f"Description: {test_case.test_description}\n"
            output += f"Preconditions: {test_case.preconditions}\n"
            output += f"Test Steps: {test_case.test_steps}\n"
            output += f"Expected Results: {test_case.expected_results}\n"
            output += f"Priority: {test_case.priority.value}\n"
            # output += f"Dependencies: {test_case.dependencies}\n"
            output += "\n"

    print(output)

    return output


@retry(exceptions=Exception, tries=3, delay=1, backoff=2)
async def _launch_qa_test_generation(url: str, task: str, headless: bool = False):

    browser = Browser(config=BrowserConfig(headless=headless))

    agent = Agent(
        task=task,
        llm=AGENT_LLM,
        initial_actions=[{'go_to_url': {'url': url}}],
        controller=Controller(output_model=GeneratedTestPlan),
        browser=browser,
        generate_gif=False,
    )

    # NOTE: arbitrary value to prevent infinite loops
    # Might not be enough for some cases
    output = await agent.run(max_steps=20)

    if output is None:
        raise Exception("Result is None")

    await browser.close()

    return output


async def generate_qa_tests(url: str, feature_guide: str, section: TestSection, other_sections: list[TestSection], headless: bool = False):

    # browser = Browser(config=BrowserConfig(headless=headless))

    test_categories = {
        TestCategory.POSITIVE: "Positive test cases (happy path). Scenarios that verify the system works as expected under normal or ideal conditions. These tests ensure that the software behaves correctly when given valid and expected inputs.",
        TestCategory.NEGATIVE: "Negative test cases (error handling). Focus on only testing the system when given incorrect inputs or unexpected user actions. Note that external factors should not be considered (e.g no internet connection, no database connection, etc.).",
        TestCategory.BOUNDARY: "Boundary test cases (edge cases). Focus on testing the edge limits of input fields or conditions. Ensure that the system correctly handles values at the minimum, maximum, just inside, just outside, and exact boundary limits of an acceptable range. Note that external factors should not be considered (e.g no internet connection, no database connection, etc.).",
        TestCategory.INTEGRATION: "Integration test cases (cross-feature interactions). Focus on testing the interaction between different modules, components, or systems to ensure they work together as expected. Verify data flow and communication between dependent systems to detect integration issues.",

        # NOTE: for now we won't test performance related issues
        # TestCategory.PERFORMANCE: "Performance test cases (load and stress testing). Focus on testing the system's ability to handle high loads or stress conditions. Ensure that the system can handle a large number of users or transactions without performance degradation.",
    }

    task_text = """\
You are an experienced QA Test Engineer. Your task is to create a comprehensive test suite for the provided section based on the provided feature guide.

Section to test: {section_name}
Description: {section_description}
(Note that while the description mentions some tests, you should generate as many tests as needed for the provided test category.)

The following sections are already tested and should not be tested again:
{other_sections}

Please generate a structured test plan for the following test category: {test_category_description}
Make sure to cover all the test cases for the provided test category ({test_category_name}).

For each test case, provide:
- Unique ID (e.g., TC_ADD_CUST_001)
- Test case category ({test_categories})
- Test description
- Preconditions
- Test steps (numbered)
- Expected results
- Priority level (Critical/High/Medium/Low/Lowest)
- Any dependencies or special requirements

To help you generate the test cases, here is the feature guide:
{feature_guide}

Additional requirements:
- Use clear, actionable language
- Don't make any assumption, verify by yourself
- When verifying data-related features, make sure to verify that the data is actually saved and persisted in the database by reloading the page (specify it in the steps of the test case).
- Write as many test cases as needed for the provided test category.
"""

    coroutines = {
        test_category: _launch_qa_test_generation(
            url=url,
            task=task_text.format(
                test_categories="/".join([test_category.value for test_category in TestCategory]),
                test_category_name=test_category.value,
                test_category_description=test_category_description,
                feature_guide=feature_guide,
                section_name=section.name,
                section_description=section.description,
                other_sections="\n".join([f"* {other_section.name}: {other_section.description}" for other_section in other_sections]),
            ),
            headless=headless,
        )
        for (test_category, test_category_description) in test_categories.items()
    }

    histories = await asyncio.gather(*[_coroutine for _coroutine in coroutines.values()])
    raw_results = [history.final_result() for history in histories]

    output = {}

    for raw_result, (test_category, _), history in zip(raw_results, test_categories.items(), histories):

        if raw_result is None:
            print(f"Result for {test_category=} is None", end="\n\n")
            print("History:")
            print(history.action_results())
            continue

        try:
            # Parse the raw result as GeneratedTestPlan
            test_plan = GeneratedTestPlan.model_validate(json.loads(raw_result))
        except ValidationError as e:
            print(f"Validation error for {test_category=}: {e}")
            print("Raw result:")
            print(raw_result)
            raise e

        # Convert each GeneratedTestCase to TestCase with additional fields
        for idx, generated_case in enumerate(test_plan.test_cases):

            test_case = TestCase(
                **generated_case.model_dump(),  # Copy all fields from GeneratedTestCase
                test_id=f"TC_{test_category.name.upper()}_{idx + 1:03d}",  # Generate unique ID
                test_category=test_category  # Add category
            )

            if test_category not in output:
                output[test_category] = []

            output[test_category].append(test_case)

    return TestPlan(
        test_cases=output,
    )


async def verify_test_plan(test_plan: TestPlan, documentation: str):

    result = await AGENT_LLM.agenerate(messages=[
        [
            HumanMessage(
                content=(
                    "Based on the following documentation and generated test plan, verify if the test plan is complete and covers all the features.\n\n"
                    "Documentation: " + documentation + "\n\n"
                    "Test Plan: " + test_plan.model_dump_json() + "\n\n"
                    "Notes:\n"
                    f"* Only the following test categories should be considered: {', '.join([test_category.value for test_category in TestCategory])}.\n"
                    "* If the test plan is complete, return 'Complete'. If it's not complete, write a detailed report of what is missing and what should be added.\n"
                )
            )
        ],
    ])

    return result.generations[0][-1].text
