services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - default
    volumes:
      - ./app/src:/app/src
    environment:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ["fastapi", "dev", "--reload", "src/main.py", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./api/src:/app/src
    ports:
      - "8000:8000"
    networks:
      - default
      - api-tm_shared_network
    environment:
      - APP_URL=${APP_URL:-http://localhost:3000}
      - POSTGRES_DB=${POSTGRES_DB:-test}
      - POSTGRES_USER=${POSTGRES_USER:-test}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-test}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-defaultsecret}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY:-defaultsecret}
      - TASK_MANAGER_URL=${TASK_MANAGER_URL:-http://task-manager:9000}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-test}
      - POSTGRES_USER=${POSTGRES_USER:-test}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-test}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-test}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    networks:
      - default
    environment:
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}


networks:
  default:
  api-tm_shared_network: # docker network create api-tm_shared_network
    external: true
