services:
  validate_url_lambda:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: src.validate_url.handler.lambda_handler
    ports:
      - "8081:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HEADLESS=true
    networks:
      - default
      - api-tm_shared_network
    mem_limit: 2048M
    cpu_count: 1.0

networks:
  default:
  api-tm_shared_network: # api and task manager shared network
    external: true