services:
  validate_url_lambda:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: src.main.lambda_handler
    ports:
      - "8081:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HEADLESS=true
      - LAMBDA_WEBHOOK_URL=http://lambda_webhook:8085/lambda-webhook
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin
      - S3_BUCKET_NAME=task-manager
      - S3_BUCKET_ENDPOINT_URL=http://minio:9000
      - SYMMETRIC_ENCRYPTION_KEY=${SYMMETRIC_ENCRYPTION_KEY:-S5ox-_h4p9NISVvQFPsAE5T-8K-SNp67GLQalO75rDI=}
      - TWOCAPTCHA_API_KEY=${TWOCAPTCHA_API_KEY:-unknown}
    networks:
      - default
      - api-tm_shared_network
    mem_limit: 2048M
    cpu_count: 1.0

networks:
  default:
  api-tm_shared_network: # api and task manager shared network
    external: true